[ffs]
id = "simulations.ffs.test"
comment = ""
environment = "ffs"

[ffs.executor]
type = "Executor"
arguments = { }
[ffs.executor.integrator.global]
type = "OpenmmIntegrator"

[ffs.executor.integrator.global.arguments]
openmm_type = "LangevinIntegrator"
openmm_arguments = [ 900.0, 0.001, 0.001 ]

[[ffs.executor.integrator.global.arguments.potentials]]
path = "/home/leonid/potentials/AlHe_Men_exp6_eam_openmm0.xml"
particles = { 1 = [[ 1 ]], 2 = [[ 2 ]] }

[[ffs.executor.integrator.individual]]
platform = { name = "HIP", Precision = "mixed", DeviceIndex = "0" }

[[ffs.executor.integrator.individual]]
platform = { name = "HIP", Precision = "mixed", DeviceIndex = "3" }


[ffs.parameter]
type = "Parameter"
[ffs.parameter.arguments]
index = 0

[ffs.state]
path = "/home/leonid/systems/ffs/test.lammpsdump"
radius = 9.0
seed = 4
trsh = 0.5

[ffs.stopcriterion]
type = "StopCriterion"
[ffs.stopcriterion.arguments]
val = 1

[ffs.barriers]
# 17038 -- 17517
barriers = [
    17100,
    17200,
    17300,
    17400,
    17500,
]

[ffs.disturbance]
type = "VelocityDisturbance"
[ffs.disturbance.arguments]
seed = 4

[ffs.steps]
run = 10000
mean = 1000
